name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node: [ 22 ]

    steps:
      - name: Setup Environment
        run: |
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get -qq update
          sudo apt-get install -y libgbm1 ttf-mscorefonts-installer
          sudo fc-cache -fv
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Lint packages
        run: npm run lint
      - name: Test packages
        run: npm test
        env:
          CONVERT_SVG_LAUNCH_OPTIONS: '{"args": ["--no-sandbox", "--disable-setuid-sandbox"]}'
