name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Microsoft fonts
        run: |
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get -qq update
          sudo apt-get install -y ttf-mscorefonts-installer
          sudo fc-cache -fv
      - name: Install dependencies
        run: |
          npm install
          npm run bootstrap
      - name: Test packages
        run: npm test
